use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub struct Chapter {
    pub id: &'static str,
    pub subject_id: &'static str,
    pub order: i32,
    pub name: &'static str,
    pub no_requirement: bool,
}

pub fn chapters_for_subject(subject_id: &str) -> Vec<Chapter> {
    match subject_id {
        "pharmaceutics" => PHARMACEUTICS_CHAPTERS.to_vec(),
        "pharmacology" => PHARMACOLOGY_CHAPTERS.to_vec(),
        "medicinal_chemistry" => MEDICINAL_CHEMISTRY_CHAPTERS.to_vec(),
        "pharmaceutical_analysis" => PHARMACEUTICAL_ANALYSIS_CHAPTERS.to_vec(),
        _ => Vec::new(),
    }
}

pub fn all_chapters() -> Vec<Chapter> {
    [
        PHARMACEUTICS_CHAPTERS.as_slice(),
        PHARMACOLOGY_CHAPTERS.as_slice(),
        MEDICINAL_CHEMISTRY_CHAPTERS.as_slice(),
        PHARMACEUTICAL_ANALYSIS_CHAPTERS.as_slice(),
    ]
    .concat()
}

const PHARMACEUTICS_CHAPTERS: [Chapter; 22] = [
    chapter("pharmaceutics-01", "pharmaceutics", 1, "第一章 绪论", false),
    chapter(
        "pharmaceutics-02",
        "pharmaceutics",
        2,
        "第二章 药物的物理化学相互作用",
        false,
    ),
    chapter(
        "pharmaceutics-03",
        "pharmaceutics",
        3,
        "第三章 药物溶解与溶出及释放",
        false,
    ),
    chapter(
        "pharmaceutics-04",
        "pharmaceutics",
        4,
        "第四章 药物多晶型",
        false,
    ),
    chapter(
        "pharmaceutics-05",
        "pharmaceutics",
        5,
        "第五章 表面活性剂",
        false,
    ),
    chapter(
        "pharmaceutics-06",
        "pharmaceutics",
        6,
        "第六章 微粒分散体系",
        false,
    ),
    chapter(
        "pharmaceutics-07",
        "pharmaceutics",
        7,
        "第七章 流变学基础",
        false,
    ),
    chapter(
        "pharmaceutics-08",
        "pharmaceutics",
        8,
        "第八章 药物制剂设计",
        false,
    ),
    chapter(
        "pharmaceutics-09",
        "pharmaceutics",
        9,
        "第九章 液体制剂的单元操作",
        false,
    ),
    chapter(
        "pharmaceutics-10",
        "pharmaceutics",
        10,
        "第十章 液体制剂",
        false,
    ),
    chapter(
        "pharmaceutics-11",
        "pharmaceutics",
        11,
        "第十一章 注射剂",
        false,
    ),
    chapter(
        "pharmaceutics-12",
        "pharmaceutics",
        12,
        "第十二章 粉体学基础（不做要求）",
        true,
    ),
    chapter(
        "pharmaceutics-13",
        "pharmaceutics",
        13,
        "第十三章 固体制剂的单元操作",
        false,
    ),
    chapter(
        "pharmaceutics-14",
        "pharmaceutics",
        14,
        "第十四章 固体制剂",
        false,
    ),
    chapter(
        "pharmaceutics-15",
        "pharmaceutics",
        15,
        "第十五章 皮肤给药制剂",
        false,
    ),
    chapter(
        "pharmaceutics-16",
        "pharmaceutics",
        16,
        "第十六章 黏膜给药制剂",
        false,
    ),
    chapter(
        "pharmaceutics-17",
        "pharmaceutics",
        17,
        "第十七章 缓控释制剂",
        false,
    ),
    chapter(
        "pharmaceutics-18",
        "pharmaceutics",
        18,
        "第十八章 靶向制剂",
        false,
    ),
    chapter(
        "pharmaceutics-19",
        "pharmaceutics",
        19,
        "第十九章 生物技术药物制剂",
        false,
    ),
    chapter(
        "pharmaceutics-20",
        "pharmaceutics",
        20,
        "第二十章 现代中药制剂（不做要求）",
        true,
    ),
    chapter(
        "pharmaceutics-21",
        "pharmaceutics",
        21,
        "第二十一章 药物制剂的稳定性",
        false,
    ),
    chapter(
        "pharmaceutics-22",
        "pharmaceutics",
        22,
        "第二十二章 药品包装（不做要求）",
        true,
    ),
];

const PHARMACOLOGY_CHAPTERS: [Chapter; 48] = [
    chapter("pharmacology-01", "pharmacology", 1, "第一章 绪言", false),
    chapter(
        "pharmacology-02",
        "pharmacology",
        2,
        "第二章 药物代谢动力学",
        false,
    ),
    chapter(
        "pharmacology-03",
        "pharmacology",
        3,
        "第三章 药物效应动力学",
        false,
    ),
    chapter(
        "pharmacology-04",
        "pharmacology",
        4,
        "第四章 影响药物效应的因素",
        false,
    ),
    chapter(
        "pharmacology-05",
        "pharmacology",
        5,
        "第五章 传出神经系统药理概论",
        false,
    ),
    chapter(
        "pharmacology-06-08-09",
        "pharmacology",
        6,
        "第六、八、九章 胆碱受体激动药和胆碱受体阻断药",
        false,
    ),
    chapter(
        "pharmacology-07",
        "pharmacology",
        7,
        "第七章 抗胆碱酯酶药和胆碱酯酶复活药",
        false,
    ),
    chapter(
        "pharmacology-10",
        "pharmacology",
        10,
        "第十章 肾上腺素受体激动药",
        false,
    ),
    chapter(
        "pharmacology-11",
        "pharmacology",
        11,
        "第十一章 肾上腺素受体阻断药",
        false,
    ),
    chapter(
        "pharmacology-12",
        "pharmacology",
        12,
        "第十二章 中枢神经系统药理学概论（不做要求）",
        true,
    ),
    chapter(
        "pharmacology-13",
        "pharmacology",
        13,
        "第十三章 全身麻醉药（不做要求）",
        true,
    ),
    chapter(
        "pharmacology-14",
        "pharmacology",
        14,
        "第十四章 局部麻醉药（不做要求）",
        true,
    ),
    chapter(
        "pharmacology-15",
        "pharmacology",
        15,
        "第十五章 镇静催眠药和促觉醒药",
        false,
    ),
    chapter(
        "pharmacology-16",
        "pharmacology",
        16,
        "第十六章 抗癫痫药和抗惊厥药",
        false,
    ),
    chapter(
        "pharmacology-17",
        "pharmacology",
        17,
        "第十七章 治疗中枢神经系统退行性疾病药",
        false,
    ),
    chapter(
        "pharmacology-18",
        "pharmacology",
        18,
        "第十八章 抗精神失常药",
        false,
    ),
    chapter(
        "pharmacology-19",
        "pharmacology",
        19,
        "第十九章 中枢镇痛药",
        false,
    ),
    chapter(
        "pharmacology-20",
        "pharmacology",
        20,
        "第二十章 解热镇痛抗炎药和抗痛风药",
        false,
    ),
    chapter(
        "pharmacology-21",
        "pharmacology",
        21,
        "第二十一章 离子通道概论及钙通道阻滞药",
        false,
    ),
    chapter(
        "pharmacology-22",
        "pharmacology",
        22,
        "第二十二章 抗心律失常药",
        false,
    ),
    chapter(
        "pharmacology-23",
        "pharmacology",
        23,
        "第二十三章 作用于肾素-血管紧张素系统的药物",
        false,
    ),
    chapter(
        "pharmacology-24",
        "pharmacology",
        24,
        "第二十四章 利尿药",
        false,
    ),
    chapter(
        "pharmacology-25",
        "pharmacology",
        25,
        "第二十五章 抗高血压药物",
        false,
    ),
    chapter(
        "pharmacology-26",
        "pharmacology",
        26,
        "第二十六章 治疗心力衰竭的药物",
        false,
    ),
    chapter(
        "pharmacology-27",
        "pharmacology",
        27,
        "第二十七章 抗心绞痛药",
        false,
    ),
    chapter(
        "pharmacology-28",
        "pharmacology",
        28,
        "第二十八章 抗动脉粥样硬化药",
        false,
    ),
    chapter(
        "pharmacology-29",
        "pharmacology",
        29,
        "第二十九章 作用于血液及造血系统的药物",
        false,
    ),
    chapter(
        "pharmacology-30",
        "pharmacology",
        30,
        "第三十章 影响自体活性物质的药物",
        false,
    ),
    chapter(
        "pharmacology-31",
        "pharmacology",
        31,
        "第三十一章 作用于呼吸系统的药物",
        false,
    ),
    chapter(
        "pharmacology-32",
        "pharmacology",
        32,
        "第三十二章 作用于消化系统的药物",
        false,
    ),
    chapter(
        "pharmacology-33",
        "pharmacology",
        33,
        "第三十三章 子宫平滑肌兴奋药和抑制药（不做要求）",
        true,
    ),
    chapter(
        "pharmacology-34",
        "pharmacology",
        34,
        "第三十四章 性激素类药及避孕药（不做要求）",
        true,
    ),
    chapter(
        "pharmacology-35",
        "pharmacology",
        35,
        "第三十五章 肾上腺皮质激素类药物",
        false,
    ),
    chapter(
        "pharmacology-36",
        "pharmacology",
        36,
        "第三十六章 甲状腺激素和抗甲状腺药",
        false,
    ),
    chapter(
        "pharmacology-37",
        "pharmacology",
        37,
        "第三十七章 治疗糖尿病的药物",
        false,
    ),
    chapter(
        "pharmacology-38",
        "pharmacology",
        38,
        "第三十八章 抗骨质疏松药（不做要求）",
        true,
    ),
    chapter(
        "pharmacology-39",
        "pharmacology",
        39,
        "第三十九章 抗菌药物概论",
        false,
    ),
    chapter(
        "pharmacology-40",
        "pharmacology",
        40,
        "第四十章 β-内酰胺类抗生素",
        false,
    ),
    chapter(
        "pharmacology-41",
        "pharmacology",
        41,
        "第四十一章 大环内酯类、林可霉素类及多肽类抗生素",
        false,
    ),
    chapter(
        "pharmacology-42",
        "pharmacology",
        42,
        "第四十二章 氨基糖苷类抗生素",
        false,
    ),
    chapter(
        "pharmacology-43",
        "pharmacology",
        43,
        "第四十三章 四环素类及氯霉素类",
        false,
    ),
    chapter(
        "pharmacology-44",
        "pharmacology",
        44,
        "第四十四章 人工合成抗菌药",
        false,
    ),
    chapter(
        "pharmacology-45",
        "pharmacology",
        45,
        "第四十五章 抗病毒药（不做要求）",
        true,
    ),
    chapter(
        "pharmacology-46",
        "pharmacology",
        46,
        "第四十六章 抗真菌药（不做要求）",
        true,
    ),
    chapter(
        "pharmacology-47",
        "pharmacology",
        47,
        "第四十七章 抗结核病药及抗麻风病药",
        false,
    ),
    chapter(
        "pharmacology-48",
        "pharmacology",
        48,
        "第四十八章 抗寄生虫药（不做要求）",
        true,
    ),
    chapter(
        "pharmacology-49",
        "pharmacology",
        49,
        "第四十九章 抗恶性肿瘤药",
        false,
    ),
    chapter(
        "pharmacology-50",
        "pharmacology",
        50,
        "第五十章 影响免疫功能的药物（不做要求）",
        true,
    ),
];

const MEDICINAL_CHEMISTRY_CHAPTERS: [Chapter; 14] = [
    chapter(
        "medicinal_chemistry-01",
        "medicinal_chemistry",
        1,
        "第一章 绪论",
        false,
    ),
    chapter(
        "medicinal_chemistry-02",
        "medicinal_chemistry",
        2,
        "第二章 新药研究的基本原理与方法",
        false,
    ),
    chapter(
        "medicinal_chemistry-03",
        "medicinal_chemistry",
        3,
        "第三章 药物代谢",
        false,
    ),
    chapter(
        "medicinal_chemistry-04",
        "medicinal_chemistry",
        4,
        "第四章 中枢神经系统药物",
        false,
    ),
    chapter(
        "medicinal_chemistry-05",
        "medicinal_chemistry",
        5,
        "第五章 外周神经系统药物",
        false,
    ),
    chapter(
        "medicinal_chemistry-06",
        "medicinal_chemistry",
        6,
        "第六章 循环系统药物",
        false,
    ),
    chapter(
        "medicinal_chemistry-07",
        "medicinal_chemistry",
        7,
        "第七章 消化系统药物",
        false,
    ),
    chapter(
        "medicinal_chemistry-08",
        "medicinal_chemistry",
        8,
        "第八章 解热镇痛药、非甾体抗炎药及抗痛风药",
        false,
    ),
    chapter(
        "medicinal_chemistry-09",
        "medicinal_chemistry",
        9,
        "第九章 抗肿瘤药",
        false,
    ),
    chapter(
        "medicinal_chemistry-10",
        "medicinal_chemistry",
        10,
        "第十章 抗生素",
        false,
    ),
    chapter(
        "medicinal_chemistry-11",
        "medicinal_chemistry",
        11,
        "第十一章 合成抗菌药及其他抗感染药",
        false,
    ),
    chapter(
        "medicinal_chemistry-12",
        "medicinal_chemistry",
        12,
        "第十二章 降血糖药、骨质疏松症治疗药物及利尿药",
        false,
    ),
    chapter(
        "medicinal_chemistry-13",
        "medicinal_chemistry",
        13,
        "第十三章 激素类药物",
        false,
    ),
    chapter(
        "medicinal_chemistry-14",
        "medicinal_chemistry",
        14,
        "第十四章 维生素（不做要求）",
        true,
    ),
];

const PHARMACEUTICAL_ANALYSIS_CHAPTERS: [Chapter; 26] = [
    chapter(
        "pharmaceutical_analysis-01",
        "pharmaceutical_analysis",
        1,
        "第一章 药物分析概要",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-02",
        "pharmaceutical_analysis",
        2,
        "第二章 药品标准与药典",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-03",
        "pharmaceutical_analysis",
        3,
        "第三章 药物的鉴别试验",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-04",
        "pharmaceutical_analysis",
        4,
        "第四章 药物质量控制的检查项目",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-05",
        "pharmaceutical_analysis",
        5,
        "第五章 原料药的重点分析项目",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-06",
        "pharmaceutical_analysis",
        6,
        "第六章 药物制剂的重点分析项目",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-07",
        "pharmaceutical_analysis",
        7,
        "第七章 药物的稳定性试验与分析",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-08",
        "pharmaceutical_analysis",
        8,
        "第八章 药物的分析方法与验证",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-09",
        "pharmaceutical_analysis",
        9,
        "第九章 体内药物的分析评价",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-10",
        "pharmaceutical_analysis",
        10,
        "第十章 芳酸类非甾体抗炎药物的分析",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-11",
        "pharmaceutical_analysis",
        11,
        "第十一章 青蒿素类抗疟药的分析（不做要求）",
        true,
    ),
    chapter(
        "pharmaceutical_analysis-12",
        "pharmaceutical_analysis",
        12,
        "第十二章 苯乙胺类拟肾上腺素类药物的分析",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-13",
        "pharmaceutical_analysis",
        13,
        "第十三章 对氨基苯甲酸酯和酰苯胺类局麻药物的分析",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-14",
        "pharmaceutical_analysis",
        14,
        "第十四章 二氢吡啶类钙通道阻滞药物的分析（不做要求）",
        true,
    ),
    chapter(
        "pharmaceutical_analysis-15",
        "pharmaceutical_analysis",
        15,
        "第十五章 苯并二氮杂䓬类镇静催眠药物的分析（不做要求）",
        true,
    ),
    chapter(
        "pharmaceutical_analysis-16",
        "pharmaceutical_analysis",
        16,
        "第十六章 维生素类药物的分析（不做要求）",
        true,
    ),
    chapter(
        "pharmaceutical_analysis-17",
        "pharmaceutical_analysis",
        17,
        "第十七章 甾体激素类药物的分析",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-18",
        "pharmaceutical_analysis",
        18,
        "第十八章 抗生素类药物的分析",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-19",
        "pharmaceutical_analysis",
        19,
        "第十九章 替尼类抗肿瘤药物的分析（不做要求）",
        true,
    ),
    chapter(
        "pharmaceutical_analysis-20",
        "pharmaceutical_analysis",
        20,
        "第二十章 核苷类抗病毒药物的分析（不做要求）",
        true,
    ),
    chapter(
        "pharmaceutical_analysis-21",
        "pharmaceutical_analysis",
        21,
        "第二十一章 吩噻嗪类抗精神病药物的分析（不做要求）",
        true,
    ),
    chapter(
        "pharmaceutical_analysis-22",
        "pharmaceutical_analysis",
        22,
        "第二十二章 莨菪烷类抗胆碱药物的分析",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-23",
        "pharmaceutical_analysis",
        23,
        "第二十三章 中药分析概论",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-24",
        "pharmaceutical_analysis",
        24,
        "第二十四章 生物药物的分析概要",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-25",
        "pharmaceutical_analysis",
        25,
        "第二十五章 药学研究的通用格式资料与要求",
        false,
    ),
    chapter(
        "pharmaceutical_analysis-26",
        "pharmaceutical_analysis",
        26,
        "第二十六章 药物分析新技术概述（不做要求）",
        true,
    ),
];

const fn chapter(
    id: &'static str,
    subject_id: &'static str,
    order: i32,
    name: &'static str,
    no_requirement: bool,
) -> Chapter {
    Chapter {
        id,
        subject_id,
        order,
        name,
        no_requirement,
    }
}
